### ISSUE TITLE
Size of bounding box dimBouBoxension 0 is not 4. Got 1 in shape [1, 10]

### ISSUE THREAD

**Issue by sherrylsin20** [am15h/tflite_flutter_helper#43]
I'm using custom SSD Mobilenet V2 model and got an error on this part of the code:

![image](https://user-images.githubusercontent.com/62754325/143013827-27e3c7e5-7954-4555-9aca-f1986cdf7fc5.png)

The error goes like this:

`Invalid argument(s): Axis 3 is not in range (-(D+1), D), where D is the number of dimensions of input tensor (shape=[1, 10])
E/flutter (16839): #0      SupportPreconditions.checkArgument (package:tflite_flutter_helper/src/common/support_preconditions.dart:16:7)
E/flutter (16839): #1      BoundingBoxUtils.convert (package:tflite_flutter_helper/src/image/bounding_box_utils.dart:64:26)
E/flutter (16839): #2      Classifier.predict (package:object_detection/tflite/classifier.dart:152:45)
E/flutter (16839): #3      IsolateUtils.entryPoint (package:object_detection/utils/isolate_utils.dart:45:51)
E/flutter (16839): <asynchronous suspension>`

So i changed the value from 2 to 0 but got this error instead

`[ERROR:flutter/runtime/dart_isolate.cc(1138)] Unhandled exception:
E/flutter (19024): Invalid argument(s): Size of bounding box dimBouBoxension 0 is not 4. Got 1 in shape [1, 10]
E/flutter (19024): #0      SupportPreconditions.checkArgument (package:tflite_flutter_helper/src/common/support_preconditions.dart:16:7)
E/flutter (19024): #1      BoundingBoxUtils.convert (package:tflite_flutter_helper/src/image/bounding_box_utils.dart:74:26)
E/flutter (19024): #2      Classifier.predict (package:object_detection/tflite/classifier.dart:152:45)
E/flutter (19024): #3      IsolateUtils.entryPoint (package:object_detection/utils/isolate_utils.dart:45:51)
E/flutter (19024): <asynchronous suspension>`

Is there anything wrong with my model?

**Comment by Guynullin** [comment]
Hi, I have the same problem : ( and I have the same outputs when  i changed the value to 0.
But when I changed the value to 1 I got the following error - 
"Size of bounding box dimBouBoxension 1 is not 4. Got 10 in shape [1, 10]"

**Comment by Guynullin** [comment]
@sherrylsin20 
have you been able to solve your problem?

**Comment by ninad7cos** [comment]
> @sherrylsin20 have you been able to solve your problem?
Is there any solution for this?

**Comment by nugaysamil** [comment]
is there any solution for this code?
