### ISSUE TITLE
Audio Classification for iOS can not work.

### ISSUE THREAD

**Issue by zxl777** [am15h/tflite_flutter_helper#45]
I tried to run Audio Classification sample on an iPhone device, but the following error was reported.

```
2021-12-07 21:30:21.345386+0800 Runner[6489:1451148] Metal API Validation Enabled
2021-12-07 21:30:21.620632+0800 Runner[6489:1451148] Writing analzed variants.
2021-12-07 21:30:23.421563+0800 Runner[6489:1451433] flutter: Observatory listening on http://127.0.0.1:65483/ofEKVF1edXI=/
2021-12-07 21:30:24.374794+0800 Runner[6489:1451408] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method initializeRecorder on channel com.tfliteflutter.tflite_flutter_helper:methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#2      _MyAppState.initPlugin (package:audio_classification/main.dart:80:5)
<asynchronous suspension>
2021-12-07 21:30:24.397613+0800 Runner[6489:1451408] Op builtin_code out of range: 135. **Are you using old TFLite binary with newer model?**
2021-12-07 21:30:24.397672+0800 Runner[6489:1451408] Registration failed.
2021-12-07 21:30:24.398182+0800 Runner[6489:1451408] flutter: Unable to create interpreter, Caught Exception: Invalid argument(s): Unable to create interpreter.
2021-12-07 21:30:25.095256+0800 Runner[6489:1451408] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled
```

**Comment by zxl777** [comment]
I found out that there is no swift code written for iOS yet. When will it be compatible with iOS?

**Comment by Subfly** [comment]
It seems like repo owner abondoned the ios side
